name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request_pipeline:
    name: Pull Request Pipeline
    runs-on: ubuntu-latest
    container: ghcr.io/realm/swiftlint:latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: swiftlint --fix