name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: ghcr.io/realm/swiftlint:latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: swiftlint --fix